version: "2"

services:

  # Image Containing DPS and the Model Repo
  dps_integration:
    container_name: ps_dps_integration
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/dps-integration
    volumes:
      - /etc/opt/ericsson/ERICmodeldeployment/data
      - /etc/opt/ericsson/ERICmodeldeployment/models      
      - ./dps-integration/config:/opt/ericsson/docker/config:ro
    hostname: db1-service

  # Image containing PostgreSQL Database Server used by Service Framework
  postgres:
    container_name: ps_postgres
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/postgres
    hostname: postgresql-server

  # Image containing OpenDJ (LDAP Server) and all openidm policies
  opendj:
    container_name: ps_opendj
    build: ./opendj-image
    volumes:
      - ./ldifs:/docker-entrypoint-init.d:ro

  # Apache docker image with mod_cluster enabled
  apache:
    container_name: ps_apache
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/apache-httpd-enm
    hostname: apache-host
    ports:
      - "6666:6666"
      - "${enm.launcher.port}:80"
    volumes:
      - ./apache-http-enm/config:/opt/ericsson/docker/config
      - ./apache-http-enm/conf:/opt/ericsson/docker/config/httpd
      - ${apps.directory}:/ericsson/tor/data/apps:rw

  # Image containing JBoss AS server
  jboss:
    container_name: ps_jboss
    build: ./jboss-image
    links:
      - postgres:postgresql-server
      - dps_integration:db1-service
      - opendj:ldap-remote
      - opendj:ldap-local
      - apache:apache-host
    volumes_from:
      - dps_integration
      - opendj
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1536m -XX:PermSize=128m -XX:MaxPermSize=512m -Ddps_ignore_mediation=true
    ports:
      - "9999:9999"
      - "9990:9990"
      - "8080:8080"
      - "8787:8787"
    volumes:
      - ./jboss-image/config:/opt/ericsson/docker/config
      - ${apps.directory}:/ericsson/tor/data/apps:rw

  # Image for correcting permissions on volumes
  cleanup:
    container_name: ps_cleanup
    build: ./cleanup
    volumes:
      - ${apps.directory}:/tmp/volume_mount_a:rw